### PR TITLE
Added manage-project.html skeleton

### PR DESCRIPTION
**Pull request by sschubert28**

### CODE REVIEW

**Review by aavenzornav — COMMENTED** [review]
This looks very tropical

**Review by aavenzornav — APPROVED** [review]
This is more tropical

**Review by YasashiisGod — APPROVED** [review]
LOOOKS AMAZING WOWWWW

**Review by YasashiisGod — CHANGES_REQUESTED** [review]
THIS IS DOO DOO CHANGE NOW PLEASE

**Review by YasashiisGod — APPROVED** [review]
I LOVE IT THIS IS SO MUCH MORE 

> **_TROPICAL_**

**Pull request closed without merging**
